(()=>{'use strict';
const KEY='gfdPatientProfileV228',STYLE='gfdAgeContextV240Style';
function load(){try{return JSON.parse(sessionStorage.getItem(KEY)||'{}')||{}}catch(e){return{}}}
function save(p){try{sessionStorage.setItem(KEY,JSON.stringify(p))}catch(e){};try{document.dispatchEvent(new CustomEvent('gfd:patient-context',{detail:{...p}}))}catch(e){}}
function calcDOB(v){if(!v)return null;const d=new Date(v+'T12:00:00'),now=new Date();if(Number.isNaN(d.getTime())||d>now)return null;let y=now.getFullYear()-d.getFullYear(),m=now.getMonth()-d.getMonth();if(now.getDate()<d.getDate())m--;if(m<0){y--;m+=12}return y<2?{age:y*12+m,ageUnit:'months',years:(y*12+m)/12}:{age:y,ageUnit:'years',years:y}}
function years(p){if(p.age===''||p.age==null)return null;const n=Number(p.age);return Number.isFinite(n)?(p.ageUnit==='months'?n/12:n):null}
function ageLabel(p){const y=years(p);if(y==null)return'';if(p.ageUnit==='months')return p.age+' mo';return 'Age '+p.age}
function injectStyle(){if(document.getElementById(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent=`
#gfdAgePanel{margin:10px 0;padding:12px;border:1px solid #cbd5e1;border-radius:12px;background:#f8fafc}.gfd-age-tabs{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-bottom:9px}.gfd-age-tabs button{min-height:42px;border:1px solid #cbd5e1;border-radius:9px;background:#fff;color:#173a5e;font-weight:900}.gfd-age-tabs button.on{background:#173a5e;color:#fff;border-color:#173a5e}.gfd-age-row{display:grid;grid-template-columns:1fr auto;gap:7px}.gfd-age-row input,.gfd-age-row select{width:100%;min-height:44px;border:1px solid #cbd5e1;border-radius:9px;padding:9px;font-size:16px;background:#fff;color:#111827}.gfd-age-help{margin-top:7px;font-size:11px;line-height:1.35;color:#64748b}.gfd-age-badge{display:inline-block;margin-top:8px;border-radius:999px;background:#dbeafe;color:#173a5e;padding:5px 8px;font-size:12px;font-weight:900}.gfd-age-clinical{margin:8px 0;padding:9px 11px;border-radius:10px;border-left:4px solid #2f6690;background:#eff6ff;font-size:13px;line-height:1.4}.gfd-age-clinical.warn{border-left-color:#f59e0b;background:#fffbeb}.gfd-age-clinical.danger{border-left-color:#e11d48;background:#fff1f2}
body.dark-mode #gfdAgePanel{background:#111827;border-color:#475569}body.dark-mode .gfd-age-tabs button,body.dark-mode .gfd-age-row input,body.dark-mode .gfd-age-row select{background:#0f172a;color:#f1f5f9;border-color:#475569}body.dark-mode .gfd-age-tabs button.on{background:#2f6690}body.dark-mode .gfd-age-help{color:#cbd5e1}body.dark-mode .gfd-age-clinical{background:#102a43;color:#dbeafe}body.dark-mode .gfd-age-clinical.warn{background:#33250d;color:#fef3c7}body.dark-mode .gfd-age-clinical.danger{background:#321820;color:#ffe4e6}
`;document.head.appendChild(s)}
function panel(sheet){if(!sheet||sheet.querySelector('#gfdAgePanel'))return;const p=load(),box=document.createElement('div');box.id='gfdAgePanel';let method=p.ageSource==='dob'?'dob':'reported';
 box.innerHTML=`<div class="gfd-age-tabs"><button type="button" data-m="reported">Reported Age</button><button type="button" data-m="dob">Date of Birth</button></div><div class="gfd-age-entry"></div><div class="gfd-age-help">Age is shared across Adult and Peds and is available to age-dependent protocols, medication references, and calculators. DOB is used only to calculate age.</div><div class="gfd-age-badge" hidden></div>`;
 const anchor=sheet.querySelector('.gfd-prof-grid,.gfd-prof-field');(anchor||sheet.firstElementChild)?.before(box);
 const render=()=>{box.querySelectorAll('[data-m]').forEach(b=>b.classList.toggle('on',b.dataset.m===method));const e=box.querySelector('.gfd-age-entry');if(method==='dob'){e.innerHTML=`<div class="gfd-age-row"><input type="date" id="gfdDOB" aria-label="Patient date of birth" value="${p.dob||''}"></div>`;e.querySelector('#gfdDOB').onchange=ev=>{const x=calcDOB(ev.target.value);if(!x)return;p.dob=ev.target.value;p.ageSource='dob';p.age=String(x.age);p.ageUnit=x.ageUnit;save(p);badge()}}else{e.innerHTML=`<div class="gfd-age-row"><input type="number" inputmode="decimal" min="0" id="gfdReportedAge" aria-label="Reported patient age" value="${p.age||''}"><select id="gfdReportedAgeUnit"><option value="years">Years</option><option value="months">Months</option></select></div>`;e.querySelector('select').value=p.ageUnit==='months'?'months':'years';const commit=()=>{p.ageSource='reported';p.dob='';p.age=e.querySelector('input').value;p.ageUnit=e.querySelector('select').value;save(p);badge()};e.querySelector('input').oninput=commit;e.querySelector('select').onchange=commit}badge()};
 const badge=()=>{const b=box.querySelector('.gfd-age-badge'),v=ageLabel(p);b.hidden=!v;b.textContent=v?('Shared age: '+v):''};
 box.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{method=b.dataset.m;render()});render()}
function addPanel(){document.querySelectorAll('#gfdProfileSheet').forEach(panel)}
function medicationGuidance(root=document){const p=load(),y=years(p);if(y==null)return;root.querySelectorAll('.card,.detail,.protocol-body').forEach(el=>{const t=(el.textContent||'').toLowerCase();if(!t.includes('diltiazem')||el.querySelector('.gfd-age-clinical'))return;const d=document.createElement('div');d.className='gfd-age-clinical';if(y<15){d.classList.add('danger');d.textContent='Shared age: '+ageLabel(p)+' — Gladstone Diltiazem protocol lists children under age 15 as a contraindication.'}else if(y>70){d.classList.add('warn');d.textContent='Shared age: '+ageLabel(p)+' — Gladstone Diltiazem protocol: for patients over age 70, decrease dose by 5 mg.'}else{d.textContent='Shared age: '+ageLabel(p)+' — no age-specific Diltiazem adjustment is identified for this age in the displayed Gladstone protocol.'}el.prepend(d)})}
function start(){injectStyle();addPanel();medicationGuidance();new MutationObserver(()=>{addPanel();medicationGuidance()}).observe(document.body,{subtree:true,childList:true});document.addEventListener('gfd:patient-context',()=>medicationGuidance())}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();