(()=>{'use strict';
const HUB='gfd-procedure-hub-v330';
const QUICK=[
 {id:'transcutaneous-pacing-procedure',icon:'⚡',title:'Transcutaneous Pacing',sub:'TCP • symptomatic bradycardia'},
 {id:'bipap-cpap',icon:'🫁',title:'BiPAP / CPAP',sub:'Noninvasive ventilation'},
 {id:'zoll-ventilator-procedure',icon:'🌬️',title:'Z Vent',sub:'Setup • settings • alarms'},
 {id:'sedation',icon:'💉',title:'Sedation',sub:'GFD sedation procedure'},
 {id:'difficult-airway-algorithm',icon:'🫁',title:'Difficult Airway',sub:'Airway escalation algorithm'},
 {id:'needle-surgical-cricothyrotomy-procedure',icon:'⚕️',title:'Cricothyrotomy',sub:'Needle / surgical airway'},
 {id:'pleural-decompression',icon:'🫁',title:'Pleural Decompression',sub:'Tension pneumothorax procedure'},
 {id:'ez-io-insertion-procedure',icon:'🦴',title:'EZ-IO',sub:'Intraosseous access'}
];
function isProcedures(){try{return typeof cat!=='undefined'&&cat==='Procedures'}catch(e){return false}}
function styles(){if(document.getElementById(HUB+'-style'))return;const s=document.createElement('style');s.id=HUB+'-style';s.textContent=`
.gfd-proc-hub{margin:0 0 14px;padding:13px;border:1px solid #cbd5e1;border-radius:14px;background:#f8fafc;box-shadow:0 1px 4px #0000000d}.gfd-proc-hub-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-end;margin-bottom:10px}.gfd-proc-hub-head b{display:block;font-size:16px;color:#173a5e}.gfd-proc-hub-head span{display:block;margin-top:2px;font-size:11px;color:#64748b;line-height:1.3}.gfd-proc-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.gfd-proc-quick{min-width:0;min-height:64px;border:1px solid #bfd4e5;border-left:4px solid #2f6690;border-radius:11px;background:#fff;color:#173a5e;padding:10px;display:grid;grid-template-columns:30px minmax(0,1fr) auto;gap:8px;align-items:center;text-align:left;font:inherit;cursor:pointer;touch-action:manipulation}.gfd-proc-quick:active{transform:scale(.985);background:#eef6ff}.gfd-proc-icon{font-size:20px;text-align:center}.gfd-proc-copy{min-width:0}.gfd-proc-copy b{display:block;font-size:13px;line-height:1.18}.gfd-proc-copy small{display:block;margin-top:3px;font-size:10px;line-height:1.25;color:#64748b}.gfd-proc-go{font-size:20px;color:#64748b;font-weight:900}.gfd-proc-all{margin:15px 2px 8px;font-size:11px;font-weight:950;letter-spacing:.07em;text-transform:uppercase;color:#64748b}.dark-mode .gfd-proc-hub{background:#111827!important;border-color:#475569!important}.dark-mode .gfd-proc-hub-head b{color:#f1f5f9!important}.dark-mode .gfd-proc-hub-head span,.dark-mode .gfd-proc-copy small,.dark-mode .gfd-proc-go,.dark-mode .gfd-proc-all{color:#aebbd0!important}.dark-mode .gfd-proc-quick{background:#172033!important;border-color:#475569!important;border-left-color:#38bdf8!important;color:#f1f5f9!important}.dark-mode .gfd-proc-quick:active{background:#173a5e!important}@media(max-width:360px){.gfd-proc-grid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function openId(id){const fn=typeof window.openP==='function'?window.openP:null;if(!fn)return false;try{fn(id);return true}catch(e){return false}}
function bindQuickButton(b,id){let activated=false;const go=e=>{if(e){e.preventDefault();e.stopPropagation()}if(activated)return;activated=true;openId(id);setTimeout(()=>{activated=false},450)};b.addEventListener('pointerdown',go,{passive:false});b.addEventListener('click',e=>{if(activated){e.preventDefault();e.stopPropagation();return}go(e)});b.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){go(e)}})}
function build(){const hub=document.createElement('section');hub.className='gfd-proc-hub';hub.dataset.procedureHub='1';hub.innerHTML='<div class="gfd-proc-hub-head"><div><b>Quick Procedures</b><span>High-use field procedures. The complete GFD procedure list remains below.</span></div></div><div class="gfd-proc-grid"></div>';const grid=hub.querySelector('.gfd-proc-grid');for(const q of QUICK){const b=document.createElement('button');b.type='button';b.className='gfd-proc-quick';b.dataset.procedureId=q.id;b.innerHTML='<span class="gfd-proc-icon">'+q.icon+'</span><span class="gfd-proc-copy"><b>'+q.title+'</b><small>'+q.sub+'</small></span><span class="gfd-proc-go">›</span>';bindQuickButton(b,q.id);grid.appendChild(b)}return hub}
function enhance(){if(!isProcedures())return;styles();const list=document.getElementById('list');if(!list||list.classList.contains('off'))return;if(list.querySelector('[data-procedure-hub]'))return;const hub=build();list.insertBefore(hub,list.firstChild);const label=document.createElement('div');label.className='gfd-proc-all';label.textContent='All GFD Procedures';hub.insertAdjacentElement('afterend',label)}
function boot(){styles();const list=document.getElementById('list');if(!list){setTimeout(boot,100);return}enhance();new MutationObserver(()=>{requestAnimationFrame(enhance)}).observe(list,{childList:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();